config/routes.rb
require './lib/user_contraint'

Rails.application.routes.draw do
  resources :invite, only: [:index]
  resources :statements, except: [:new]
  resources :users, only: [:destroy]

  get '/auth/twitter/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy'

  get '/',
    to: 'statements#index',
    constraints: UserConstraint,
    as: :statement_root

  root to: 'home#index'
end

app/models/invite.rb
class Invite < ActiveRecord::Base
end

app/models/statement.rb
class Statement < ActiveRecord::Base
  enum status: [:inactive, :processing, :active, :complete]

  belongs_to :user
  belongs_to :suggestion

  scope :ended, ->(date = DateTime.now) { where('ending_at < ?', date) }
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  has_many :statements, dependent: :destroy

  scope :random, ->(number) { limit(number).order('RANDOM()') }
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:inactive, :active, :admin]

  has_many :statements, dependent: :destroy

  def self.create_with_omniauth(auth:)
    CreateOmniauthUser.call auth: auth
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/landing_pad_controller.rb
class LandingPadController < ApplicationController
  def index; end
  def invite; end

  def create
    SubscribeToMailChimp.call email: params[:email]
    flash[:notice] = "Check your email"
  rescue Gibbon::MailChimpError => exception
    flash[:error] = exception
  ensure
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    KeenAdapter.new.user(user).create

    session[:user_id] = user.id
    redirect_to root_path
  end

  def failure
    redirect_to root_path, error: params[:message]
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user
    @user ||= find_user || create_user
  end

  def find_user
    User.find_by(uid: auth[:uid])
  end

  def create_user
    User.create_with_omniauth(auth: auth)
  end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :find_statement, only: [:destroy]

  def index
    @active = user.statements.active.map(&StatementDecorator)
    @processing = user.statements.processing
    @complete = complete.uniq.map(&SuggestionDecorator)
    @waiting = 4 - (@active + @processing).size
  rescue
    @active = []
    @processing = []
    @complete = []
  ensure
    @new_statement = Statement.new
  end

  def create
    statement = Statement.new(statement_params)

    if statement.processing!
      FollowWorker.perform_async(statement.id, statement_params[:follow])
    end

    redirect_to root_path
  end

  def destroy
    user.statements.find(params[:id]).tap do |statement|
      statement.complete!
      UnfollowWorker.perform_async statement.id
    end

    redirect_to root_path
  end

  private

  def complete
    user.statements.complete.map(&:suggestion)
  end

  def find_statement
    @statement = user.statements.find params[:id]
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def statement_params
    params.require(:statement)
      .permit(:follow, :duration)
      .merge(user_id: user_id)
  end

  def user
    @user ||= User.find user_id
  end

  def user_id
    session[:user_id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def destroy
    unfollow && user.delete && log
    redirect_to logout_path
  end

  private

  def unfollow
    user.statements.active.each do |statement|
      statement.complete!
      UnfollowWorker.perform_async statement.id
    end
  end

  def user
    @user ||= User.find(params[:id])
  end

  def log
    KeenAdapter.new.user(user).destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/home/index.html.erb
<div id="home">
  <article>
    <h1 class="logo">Twidipity</h1>
    <h2><span>Discover Twitter</span> Follow random people every day for 24 hours</h2>
    <a href="/auth/twitter">Join</a>
  </article>
</div>

app/views/landing_pad/index.html.erb
<div class="status">
  <% if flash.any? %>
    <% flash.each do |name, msg| %>
      <%= content_tag :h3, msg %>
    <% end %>
  <% else %>
    <h3><%= link_to 'Request Invite', invite_path %></h3>
  <% end %>
</div>

<h1 class="title">Twidipity</h1>
<h2 class="subtitle">The <span>discovery</span> of <span>tweets</span></h2>
<div class="links">
  <a href="https://twitter.com/intent/tweet?original_referer=<%= root_url %>&status=The%20discovery%20of%20fortunate%20Twitter%20events%20by%20accident%20with%20@Twidipity <%= root_url %>">Share</a>
</div>

app/views/landing_pad/invite.html.erb
<%= form_tag controller: :landing_pad, action: :create do %>
  <div class="status date">
    <h3><%= signin_link %></h3>
  </div>
  <%= text_field_tag :email, nil, placeholder: 'EMAIL ADDRESS', required: true %>
  <%= submit_tag "Send", :class => "submit" %>
<% end %>

app/views/landing_pad/notify.html.erb
<%= form_tag controller: :landing_pad, action: :create do %>
  <div class="status date">
    <h3>10/01/2015</h3>
  </div>
  <%= text_field_tag :email, nil, placeholder: 'EMAIL ADDRESS', required: true %>
  <%= submit_tag "Send", :class => "submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Twidipity' %></title>

  <meta name="description" content="Discover Twitter by following random people for 24 hours.">
  <meta name="keywords" content="Twitter,Random,Discovery,Discover,Serendipity">
  <meta name="author" content="Insert Coffee">
  <meta name="robots" content="index, nofollow">
  <meta name="revisit-after" content="5 days">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
</head>
<body>
  <% if Rails.env.development? && content_for?(:developer) %>
    <div id='developer'>
      <%= yield :developer %>
    </div>
  <% end %>

  <content>
    <%= yield %>

    <%= yield :active %>

    <%= yield :complete %>
  </content>

  <footer>
    <%= render partial: "shared/footer" %>
  </footer>

  <% if Rails.env.production? %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', '<%= Rails.application.secrets.google_analytics %>', 'auto');
      ga('send', 'pageview');
    </script>
  <% end %>

</body>
</html>

app/views/shared/_footer.html.erb
<ul class="footer-links">
  <li><a href="http://goo.gl/forms/zZwJajJfKw" target="_blank">Feedback</a></li>
  <li><a href='https://twitter.com/intent/tweet?original_referer=<%= root_url %>&status=Join%20@Twidipity%20in%20the%20discovery%20of%20Twitter <%= root_url %>'>Share Twidipity</a></li>

  <% if session[:user_id] %>
    <li class="pull-right"><%= link_to('Delete Account', user_path(id: session[:user_id]), method: :delete, data: { confirm: 'Are you sure?' }) %></li>
    <li class="pull-right"><%= link_to 'Signout', logout_path %></li>
  <% end %>
</ul>

app/views/statements/_completed_suggestion.html.erb
<div class="grid-item">
  <%= image_tag(suggestion.profile_image_uri, alt: suggestion.screen_name, class: "grid-item-img") %>
  <div class="grid-item-name-wrapper">
    <div class="grid-action">
      <a href="#">Play</a> or <%= link_to 'Delete', '#', method: :delete %>
    </div>
    <div class="grid-item-name">
      <%= suggestion.screen_name %>
    </div>
  </div>
</div>

app/views/statements/_index.html.erb
<% if @statement.error? %>
  <% content_for(:developer) do %>
    <p><%= @statement.error %></p>
  <% end %>
<% end %>

<% content_for(:title) { 'Twidipity | Following' } %>
<% content_for(:nav) { render partial: 'nav' } %>


<h2 class='statement'>
  <%= link_to 'Unfollow', statement_path, method: :delete %>
</h2>

<ul class='suggestions'>
  <% if @statement.suggestions.any? %>
    <% @statement.suggestions.each do |suggestion| %>
      <li>
        <%= link_to(image_tag(suggestion.profile_image_uri, size: '20x20', alt: suggestion.screen_name), suggestion.uri, target: :blank) %>
      </li>
    <% end %>
  <% else %>
    <li><div class='circle'></div></li>
    <li><div class='circle'></div></li>
    <li><div class='circle'></div></li>
    <li><div class='circle'></div></li>
  <% end %>
</ul>

app/views/statements/_processing.html.erb
<div class="grid-item">
  <div class="grid-item-name-wrapper grid-loading">
    <div class="grid-item-name">
      Loading
    </div>
  </div>
</div>

app/views/statements/_statement.html.erb
<%= render partial: "suggestion", locals: { statement: statement, suggestion: statement.suggestion } %>

app/views/statements/_suggestion.html.erb
<div class="grid-item">
    <%= image_tag(suggestion.profile_image_uri, alt: suggestion.screen_name, class: "grid-item-img") %>
    <div class="grid-item-name-wrapper">
      <a href="#" class="play-pause-btn pause-btn">Pause</a>
      <div class="grid-item-name">
        <%= link_to(suggestion.uri, target: :blank, class: "grid-item-link") do %>
          @<%= suggestion.screen_name %>
        <% end %>
      </div>
      <div class="grid-item-timer">
        <% if defined?(statement) %>
          <%= distance_of_time_in_words_to_now(statement.ending_at) %>
        <% end %>
      </div>
    </div>
  <% if defined?(statement) %>
    <%= link_to 'delete', statement_path(statement), method: :delete, :class => 'grid-delete-link' %>
  <% end %>
</div>

app/views/statements/_waiting.html.erb
<div class="grid-item">
  <div class="grid-item-name-wrapper grid-item-loading">
    <div class="logo">Waiting</div>
  </div>
</div>

app/views/statements/index-old.html.erb
<% content_for(:title) { 'Twidipity | Following' } %>

<% content_for(:active) do %>
  <div class="page-divider"></div>
  
  <div class="section-2">
    <div class="column-1">
      <h2>Find more people</h2>

      <p>You will follow each person for 24 hours. Afterwards, we will unfollow them for you. If you're impatient, you can always remove them from the list manually.</p>
      <p>If you like what they Tweeted, but we unfollowed them, you can always <%= link_to('visit your history', history_path) %> and follow them again.</p>
      <p>You can only follow 4 people at a time because we want to be nice to our servers.</p>

      <%= form_for @new_statement do |f| %>
        <%= f.hidden_field :follow, value: 1 %>
        <%= f.hidden_field :duration, value: 86400 %>
        <%= f.submit 'Find another random person', :class => "btn" %>
      <% end %>
    </div>
    <div class="column-2">
    </div>
  </div>  
<% end %>

<% content_for(:complete) do %>
  <%= render partial: "suggestion", collection: @complete %>
<% end %>

app/views/statements/index.html.erb
<% content_for(:title) { 'Twidipity' } %>

<div id="statements">
  <div class="active">
    <div class="grid-item">
      <div class="grid-item-name-wrapper grid-item-add">
        <%= form_for @new_statement do |f| %>
          <%= f.hidden_field :follow, value: 1 %>
          <%= f.hidden_field :duration, value: 86400 %>
          <%= f.submit '+' %>
        <% end %>
      </div>
    </div>

    <%= render partial: "statement", collection: @active %>
    <%= render partial: "processing", collection: @processing %>

    <% @waiting.times do %>
      <%= render partial: "waiting" %>
    <% end %>
  </div>

  <div class="inactive">
    <%= render partial: "completed_suggestion", collection: @complete, as: :suggestion %>
  </div>
</div>